
# Selecting data

Numpu array allow us different ways to select data.
In `[:,:]`. The first part is for rows and second part is for columns. The `:` means to select all. `[:,:]` means to select all rows and columns. 

Let's find out more details with examples. We create an array of numbers with `numpy`.

In [10]:
import pandas as pd
import numpy as np

In [2]:
mydata = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]]
                 )

In order to select after the first row and all columns, use `[1:,:]`.

In [3]:
mydata[1:,:]


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In order to select all rows and after the second column, use `[:,2:]`.

In [5]:
mydata[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In order to select after the first row and after the second column, use `[1:,2:]`.

In [7]:
mydata[1:,2:]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

From the Pandas dataframe, you can use `df["column name"]["row index or row name"]`. You can use only a column name but not a column index whereas you can use a row name and a row index.   
We create a Pandas dataframe using numpy array `mydata` for this exercise. We add index and column names using `index` and `column`. 

In [11]:
df = pd.DataFrame(mydata)
df.index=["Row 1","Row 2","Row 3","Row 4"]
df.columns=["Col 1", "Col 2", "Col 3", "Col 4"]
print(df)

       Col 1  Col 2  Col 3  Col 4
Row 1      1      2      3      4
Row 2      5      6      7      8
Row 3      9     10     11     12
Row 4     13     14     15     16


We can select Col 1 column using the column name.

In [12]:
print(df["Col 1"])

Row 1     1
Row 2     5
Row 3     9
Row 4    13
Name: Col 1, dtype: int64


We can select the Col 1 and Col 3. Please note `[[ ]]`.

In [13]:
print(df[["Col 1","Col 3"]])

       Col 1  Col 3
Row 1      1      3
Row 2      5      7
Row 3      9     11
Row 4     13     15


Selecting Col 2 and Row 3 which is 10.

In [14]:
print(df["Col 2"]["Row 3"])

10


Using an index for the row to select the same number 10.

In [15]:
print(df["Col 2"][2])

10


One more way to select is to use `iloc` and `loc`. If you are interested to know about it, please read [this article](https://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix/).

# In Python list vs Numpy array

In [22]:
py = [[1,2,3,4],[5,6,7,8]]
print(slice(3))

slice(None, 3, None)


# Reference

- https://github.com/jakevdp/PythonDataScienceHandbook